## Imports

In [34]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn import metrics

import pandas as pd
import numpy as np

import backtrader as bt

## Data laoding from CSV
### Stockdata
* Load data from CSV

In [35]:
stock_list = pd.read_csv('clean_data.csv',sep=',')
u_symbol = stock_list['symbol'].unique()
date = pd.Series(stock_list['datetime'])
stock_list.drop(['datetime'],axis=1,inplace=True)
stock_list['date'] = date.apply(lambda x: np.datetime64(x))
stock_data = {}

for symbol in u_symbol:
    stock_data[symbol] = stock_list[stock_list['symbol'] == symbol]

stock_data[list(stock_data.keys())[0]]

open   high    low  close     volume   symbol  log_returns       date
0    32.30  33.58  32.30  32.84  7315000.0  1179.HK     0.056371 2020-09-23
1    34.08  34.20  33.50  33.73  2797160.0  1179.HK     0.026740 2020-09-24
2    33.12  33.12  32.30  32.62  3964430.0  1179.HK    -0.033462 2020-09-25
3    32.68  33.22  32.68  33.08   763500.0  1179.HK     0.014003 2020-09-28
4    33.58  34.18  33.58  33.99  2398130.0  1179.HK     0.027137 2020-09-29
..     ...    ...    ...    ...        ...      ...          ...        ...
838  29.20  29.20  28.30  28.85  2695218.0  1179.HK    -0.012059 2024-02-22
839  29.10  30.05  29.10  29.70  1548300.0  1179.HK     0.029037 2024-02-23
840  30.35  31.00  30.30  30.40  3111600.0  1179.HK     0.023296 2024-02-26
841  29.60  30.10  29.15  29.95  2316600.0  1179.HK    -0.014913 2024-02-27
842  29.75  30.10  29.35  29.35  3393460.0  1179.HK    -0.020237 2024-02-28

[843 rows x 8 columns]

In [36]:
# visualize one stock
stock_data[list(stock_data.keys())[0]].plot.scatter(x='log_returns',y='date',c='DarkBlue')

<IPython.core.display.Javascript object>

<Axes: xlabel='log_returns', ylabel='date'>

### Short-selling-reports

In [37]:
short_list = pd.read_excel('stocks_with_listings.xlsx')

## Label Rows
* read time shifted `adj_close` into `signal` such that it can be compared to current date in one row without reverse lookupQQ
* compare previous day and set 1 if stock has risen

In [38]:
# label function
# 1 lower than previous day
# 0 higher than previous day
def label_row(row):
    if (row['signal'] < 0):
        return 1
    else:
            return 0
def label_df(df):
    df['signal'] = df['log_returns'].shift(1)
    df.fillna(0)
    df['signal'] = df.apply(label_row,axis=1)
    return df

In [39]:
length = 0
amount_0 = 0
amount_1 = 0 
for ticker in stock_data:
#     stock_data[ticker]['singal'] = stock_data[ticker]['log_returns'].shift(1)
    stock_data[ticker] = label_df(stock_data[ticker])
#     signal = np.array(stock_data[ticker]['signal'])
    amount_0 = amount_0 + len(np.where(stock_data[ticker]['signal'] == 0)[0])
    amount_1 = amount_1 + len(np.where(stock_data[ticker]['signal'] == 1)[0])
print("Total amount of 0's:{0}\nTotal amount of 1's:{1}".format(amount_0,amount_1))


C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signal'] = df['log_returns'].shift(1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signal'] = df.apply(label_row,axis=1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = v

Total amount of 0's:547465
Total amount of 1's:461002


C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signal'] = df['log_returns'].shift(1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['signal'] = df.apply(label_row,axis=1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_2608\3378846765.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = v

## Create Bands

In [40]:
# for i in stock_data:
#     df = stock_data[i]
#     if(df['signal'].shape[0] < 10):
#         print(i)
#         print(df['signal'].shape)

## Filter training data

In [41]:
def nearest(items, pivot):
    return min(items, key=lambda x: abs(x - pivot))

In [42]:
stocks_after_report = {}

for index, row in short_list.iterrows():
    symbol = row['SYMBOL']
    date_report = row['Date']
    if symbol in list(stock_data.keys()):
        stock_df = stock_data[symbol]
        stock_start_date = nearest(np.array(stock_df['date']),date_report)
        condition = stock_df['date'] == stock_start_date
        start_index = stock_df.index[condition][0]
        # gets all entries of the stock after the shortselling repport for this stock has been rleases
        if(start_index > stock_df.index[-1]):
            print("start index df: {}, end index df: {}, date after report: {}".format(stock_df.index[0],stock_df.index[-1],start_index))
        result = stock_df.loc[start_index:].copy()
        # replace date with column that indicates how many days past release have passed
        incremental = np.arange(0,len(result.date))
        result['index'] = incremental
        # save each dataset
        stocks_after_report[symbol] = result


## Create Testsplit
* We create a testsplit at a certain date which allows for roughly 70% of the data to be before it for training.
* The other 30% will be after the date, we ensure this way that when we do out of sample testing that the training wasnt
"poisoned" with future data.

In [120]:
# Make sure all dates are in datetime format
short_list['Date'] = short_list['Date'].apply(lambda x: np.datetime64(x)) 
# Sort list by date ascending
short_list.sort_values(by=['Date'], inplace=True, ascending=True)
# Remove entries that arent in the dataset with 
short_list = short_list[short_list['SYMBOL'].isin(stocks_after_report)]
# Get amount of entries
sl_size = short_list.shape[0]
# Get index up to which 70% of the entries are.
position_training_block = int(sl_size*0.7)
# Create Testsplit
train_list = short_list.iloc[:position_training_block]
test_list = short_list.iloc[position_training_block:]

X_train = []
Y_train = []

X_test = []
Y_test = []

X_train_cum = np.array([[0,0]])
Y_train_cum = np.array([[0]]) 

for ticker in train_list['SYMBOL']:
    x = np.array(stocks_after_report[ticker][['index','log_returns']])
    y = np.array(stocks_after_report[ticker][['signal']].shift(1).fillna(0))
    #TODO because of the shift right our first element of y is now nan we delete the first day for both. 
    # X_train.append(np.delete(x,0))
    # Y_train.append(np.delete(y,0))
    X_train.append(x) #shape (n,2)
    Y_train.append(y) #shape (n,1)
    X_train_cum = np.append(X_train_cum,x,axis=0)
    Y_train_cum = np.append(Y_train_cum,y,axis=0)



for ticker in test_list['SYMBOL']:
    x = np.array(stocks_after_report[ticker][['index','log_returns']])
    y = np.array(stocks_after_report[ticker][['signal']])
    X_test.append(x)
    # after shift for some reason values are float
    Y_test.append(y.astype(np.float64))

print(len(X_train_cum))

211558


## Train XGB

In [116]:
# Define classifier
clf = xgb.XGBRegressor()
# ravel() returns a continious flatened array 
clf.fit(X_train_cum,Y_train_cum)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

### Insample Testing

In [118]:

def binary_convertor(value):
    if value >= 0.5:
        return 1
    else:
        return 0
for x_test, y_test in zip(X_train, Y_train):
    y_pred = clf.predict(x_test)
    y_pred_binary = list(map(binary_convertor,y_pred))
    print("Accuracy:",metrics.accuracy_score(y_test,y_pred_binary))
    print("Precision:",metrics.precision_score(y_test, y_pred_binary,pos_label=str(1),average="macro"))
    print("Recall:",metrics.recall_score(y_test, y_pred_binary,pos_label=str(1),average="macro"))


[0.34006283 0.47233194 0.627295   ... 0.4133475  0.46946433 0.48920974]
[0.44158    0.48866436 0.6584861  ... 0.14586982 0.14586982 0.14586982]
[0.49056885 0.6553537  0.26276514 ... 0.48577917 0.4656996  0.32868907]
[0.29938072 0.47233194 0.6555073  ... 0.32636258 0.423411   0.29382965]
[0.552396   0.6085773  0.63036835 ... 0.16703919 0.24530707 0.16921341]
[0.4526476  0.52646244 0.5566224  ... 0.41593167 0.21963847 0.41593167]
[0.41997135 0.40344512 0.500723   ... 0.14586982 0.14586982 0.14586982]
[0.5412514  0.4217478  0.6164861  0.5111394  0.41886646 0.57044286
 0.4013202  0.4834791  0.48856947 0.50116557 0.43494394 0.51427025
 0.5125384  0.47198075 0.63912153 0.52540535 0.4754459  0.57140744
 0.5226769  0.50148296 0.51693124 0.5057846  0.53802896 0.41788596
 0.47561327 0.4586292  0.5432657  0.30682135 0.47778615 0.4714479
 0.29364535 0.4671737  0.47817963 0.43786705 0.42931825 0.47192386
 0.44121236 0.5117475  0.5133094  0.40424833 0.48528126 0.47242135
 0.47466552 0.4546382  0.466

### Outsample Testing

In [119]:
amount_0_pred = 0
amount_1_pred = 0
amount_0 = 0
amount_1 = 0
def binary_convertor(value):
    if value >= 0.5:
        return 1
    else:
        return 0
for x_test, y_test in zip(X_test, Y_test):
    y_pred = clf.predict(x_test)
    y_pred_binary = list(map(binary_convertor,y_pred))
    amount_0 = amount_0 + len(np.where(y_test == 0)[0])
    amount_1 = amount_1 + len(np.where(y_test == 1)[0])
    amount_0_pred = amount_0_pred + len(np.where(np.array(y_pred_binary) == 0)[0])
    amount_1_pred = amount_1_pred + len(np.where(np.array(y_pred_binary) == 1)[0])
    # if(y_pred.max() > a ):
    #     a = y_pred.max()
    # if(y_pred.min() < b ):      
    # #     b = y_pred.max()
    print("Accuracy:",metrics.accuracy_score(y_test,y_pred_binary))
    print("Precision:",metrics.precision_score(y_test, y_pred_binary,pos_label=str(1),average="macro"))
    print("Recall:",metrics.recall_score(y_test, y_pred_binary,pos_label=str(1),average="macro"))
# print("Total amount of 0's:{0}\nTotal amount of 1's:{1}".format(amount_0,amount_1))
# print("Total amount of predicted 0's:{0}\nTotal amount of predicted 1's:{1}".format(amount_0_pred,amount_1_pred))

Accuracy: 0.5292682926829269
Precision: 0.5379746835443038
Recall: 0.5361022898211599
Accuracy: 0.4851138353765324
Precision: 0.48911373268234654
Recall: 0.4891486943847427
Accuracy: 0.5296229802513465
Precision: 0.5230589022757698
Recall: 0.5223411154345007
Accuracy: 0.5523465703971119
Precision: 0.5512546570238878
Recall: 0.548820582402672
Accuracy: 0.4927536231884058
Precision: 0.49642625081221575
Recall: 0.4965277777777778
Accuracy: 0.5364963503649635
Precision: 0.5330834419817471
Recall: 0.5325581395348837
Accuracy: 0.4889705882352941
Precision: 0.4911024305555556
Recall: 0.4910850184822788
Accuracy: 0.497164461247637
Precision: 0.49757614757614754
Recall: 0.4975733715103794
Accuracy: 0.4851138353765324
Precision: 0.48911373268234654
Recall: 0.4891486943847427
Accuracy: 0.48185483870967744
Precision: 0.47988910038897625
Recall: 0.4802336174920284
Accuracy: 0.486815415821501
Precision: 0.4887769086776307
Recall: 0.4889355742296919
Accuracy: 0.4536082474226804
Precision: 0.454588744

c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is igno

Recall: 0.49149831649831643
Accuracy: 0.5253456221198156
Precision: 0.5282258064516129
Recall: 0.5276785714285714
Accuracy: 0.5625
Precision: 0.5339901991450318
Recall: 0.5312980030721967
Accuracy: 0.5480769230769231
Precision: 0.557158276911
Recall: 0.5539801686590677
Accuracy: 0.6166666666666667
Precision: 0.6666666666666667
Recall: 0.6067853170189099
Accuracy: 0.5129533678756477
Precision: 0.5162337662337662
Recall: 0.5155813453685794
Accuracy: 0.7282608695652174
Precision: 0.688135593220339
Recall: 0.688135593220339
Accuracy: 0.5294117647058824
Precision: 0.5300591531755915
Recall: 0.5292841977555354
Accuracy: 0.5176470588235295
Precision: 0.52190847127556
Recall: 0.5221052631578947
Accuracy: 0.4968553459119497
Precision: 0.4934692577253902
Recall: 0.4934692577253902
Accuracy: 0.5285714285714286
Precision: 0.5146780303030303
Recall: 0.5127467105263157
Accuracy: 0.5294117647058824
Precision: 0.5326210502386906
Recall: 0.5310404499242916
Accuracy: 0.4666666666666667
Precision: 0.4711

c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\Admin\Documents\BA\notebook\venv\Lib\site-packages\sklearn\metrics\_classification.py:1549: UserWarning: Note that pos_label (set to '1') is igno

## Backtesting with backtradern

### Test Strategy

In [47]:
# Create a Stratey
class TestStrategy(bt.Strategy):

    def log(self, txt, dt=None):
        ''' Logging function for this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close
        self.log_returns = self.datas[0].log_returns
        self.index = self.datas[0].index
        
        # To keep track of pending orders
        self.order = None

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enough cash
        if order.status in [order.Completed]:
            if order.isbuy():
                self.log('BUY EXECUTED, %.2f' % order.executed.price)
            elif order.issell():
                self.log('SELL EXECUTED, %.2f' % order.executed.price)

            self.bar_executed = len(self)

        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('Order Canceled/Margin/Rejected')

        # Write down: no pending order
        self.order = None

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])
        size = self.log_returns.__len__()
    
        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return
        
        log_return_history = self.log_returns.get(ago=0,size=size)
        index_history = self.index.get(ago=0,size=size)
        series = []
        for index, log in zip(index_history, log_return_history):
            series.append([index,log])
        forecast = clf.predict(series)
        # if the predictor predicts decline (1) we sell
        if(forecast[-1] > 0.5):
            self.order = self.sell()
        else:
            self.order = self.buy()


        
        # # Check if we are in the market
        # if not self.position:
        #     #TODO recomender goes here
        #     log_return_history = self.log_returns.get(ago=0,size=size)
        #     index_history = self.index.get(ago=0,size=size)
        #     series = []
        #     for index, log in zip(index_history, log_return_history):
        #         series.append([index,log])
        #     forecast = regressor.predict(series)
        #     print(forecast)
        #     # previous close less than the previous close
        #     # BUY, BUY, BUY!!! (with default parameters)
        #     self.log('BUY CREATE, %.2f' % self.dataclose[0])
            
        #     # Keep track of the created order to avoid a 2nd order
        #     self.order = self.buy()

        # else:

        #     # Already in the market ... we might sell
        #     if len(self) >= (self.bar_executed + 5):
        #         # SELL, SELL, SELL!!! (with all possible default parameters)
        #         self.log('SELL CREATE, %.2f' % self.dataclose[0])

        #         # Keep track of the created order to avoid a 2nd order
        #         self.order = self.sell()

### Custom Data feed
We make a custom data feed to inculde the log_returns in our data. We need this to predict. 

In [48]:
class CustomFeed(bt.feeds.PandasData):
    lines = ('datetime', 'open', 'high', 'low',
             'close', 'volume', 'log_returns', 'index')
    params = (
        ('datetime', 'date'),
        ('openinterest',None),
        ('open', -1),
        ('high', -1),
        ('low', -1),
        ('close', -1),
        ('volume', -1),
        ('log_returns', -1),
        ('index', -1)
    )

In [49]:
def exec(strategy, df):
    cerebro = bt.Cerebro()
    # Add a strategy
    cerebro.addstrategy(strategy)    
    data = CustomFeed(dataname=df)
    
    # Add the Data Feed to Cerebro
    cerebro.adddata(data)

    cerebro.broker.setcash(100000.0)

    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    cerebro.run()

    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

    plot = cerebro.plot()
    for index, figure in enumerate(plot[0]):
        # return figure
        figure.savefig("figure_{}.png".format(index)) 

# ---------------------------------
test_list
exec(TestStrategy, stocks_after_report['SLI'])
# stock_data['ABAT']['date'] = stock_data['ABAT']['date'].apply(lambda x: np.datetime64(x))
# exec(TestStrategy, stock_data['ABAT'])


Starting Portfolio Value: 100000.00
2021-11-18, Close, 8.01
2021-11-19, BUY EXECUTED, 8.60
2021-11-19, Close, 9.28
2021-11-22, SELL EXECUTED, 9.68
2021-11-22, Close, 8.43
2021-11-23, SELL EXECUTED, 8.40
2021-11-23, Close, 8.70
2021-11-24, SELL EXECUTED, 9.68
2021-11-24, Close, 10.63
2021-11-26, SELL EXECUTED, 9.65
2021-11-26, Close, 9.94
2021-11-29, BUY EXECUTED, 10.58
2021-11-29, Close, 10.89
2021-11-30, SELL EXECUTED, 10.68
2021-11-30, Close, 10.43
2021-12-01, SELL EXECUTED, 11.00
2021-12-01, Close, 10.42
2021-12-02, SELL EXECUTED, 10.39
2021-12-02, Close, 10.08
2021-12-03, BUY EXECUTED, 10.19
2021-12-03, Close, 9.42
2021-12-06, BUY EXECUTED, 8.68
2021-12-06, Close, 8.57
2021-12-07, BUY EXECUTED, 9.35
2021-12-07, Close, 9.40
2021-12-08, BUY EXECUTED, 9.60
2021-12-08, Close, 9.35
2021-12-09, SELL EXECUTED, 9.60
2021-12-09, Close, 9.01
2021-12-10, SELL EXECUTED, 9.20
2021-12-10, Close, 9.04
2021-12-13, SELL EXECUTED, 9.00
2021-12-13, Close, 8.50
2021-12-14, BUY EXECUTED, 8.06
2021-12-1

<IPython.core.display.Javascript object>

In [50]:
# stock_data['ABAT']['date'] = stock_data['ABAT']['date'].apply(lambda x: np.datetime64(x))
# print(type(stock_data['ABAT']['date'].iloc[0].to_pydatetime()))
# stock_data.set_index('date', inplace=True)
# print(test_list)
# exec(TestStrategy, stock_data['SLI'])
# print(stock_data['ABAT'].head)
# print(X_test[0])
stocks_after_report['SLI']

open   high   low  close      volume symbol  log_returns       date  \
825228  9.25   9.50  6.75   8.01  18834100.0    SLI    -0.208809 2021-11-18   
825229  8.60   9.30  8.20   9.28   4827500.0    SLI     0.147171 2021-11-19   
825230  9.68   9.68  7.87   8.43   4884700.0    SLI    -0.096065 2021-11-22   
825231  8.40   9.09  8.27   8.70   2973900.0    SLI     0.031526 2021-11-23   
825232  9.68  10.74  9.18  10.63   8061600.0    SLI     0.200357 2021-11-24   
...      ...    ...   ...    ...         ...    ...          ...        ...   
825794  1.22   1.23  1.14   1.19   1250300.0    SLI    -0.016667 2024-02-22   
825795  1.22   1.22  1.12   1.20   1063900.0    SLI     0.008368 2024-02-23   
825796  1.21   1.21  1.12   1.14   1596000.0    SLI    -0.051293 2024-02-26   
825797  1.18   1.25  1.13   1.25   1914900.0    SLI     0.092115 2024-02-27   
825798  1.24   1.25  1.21   1.25    890100.0    SLI     0.000000 2024-02-28   

        signal  index  
825228       1      0  
825229       1      1  
825230       0      2  
825231       1      3  
825232       0      4  
...        ...    ...  
825794       1    566  
825795       1    567  
825796       0    568  
825797       1    569  
825798       0    570  

[571 rows x 10 columns]

In [51]:
# max_abs_scaler = preprocessing.MaxAbsScaler()
# a = []
# model_dict = {}
# for index, row in short_list.iterrows():
#     if row['SYMBOL'] in list(stocks_after_report.keys()):
#         report_release_date =  row['Date']
#         #todo replace occurances of i with symbol
#         i = symbol
#         # read df into np.array
#         X = np.array(stocks_after_report[i].drop(['signal','date'],axis=1))
#         X = max_abs_scaler.fit_transform(X)
#         Y = np.array(stocks_after_report[i]['signal'])

#         # split
#         X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)


#         model_dict[i] = {}
#         model_dict[i]['X Train'] = X_train
#         model_dict[i]['X Test'] = X_test
#         model_dict[i]['Y Train'] = y_train
#         model_dict[i]['Y Test'] = y_test
        
#         model = svm.SVC(kernel='rbf',decision_function_shape='ovo')
#         # model = svm.SVC(kernel='linear')
#         # model = svm.SVC(kernel='linear',decision_function_shape='ovo')
#         # model = svm.SVC(kernel='rbf',decision_function_shape='ovo')
#         # model = svm.SVC(kernel='poly')
#         # model = svm.SVC(kernel='poly',decision_function_shape='ovo')
#         # model = svm.SVC(kernel='sigmoid')
#         # model = svm.SVC(kernel='sigmoid',decision_function_shape='ovo')

#         # fit and test
#         try:
#             model.fit(X_train, y_train)
#             y_pred = model.predict(X_test)
#             model_dict[i]['Y Prediction'] = y_pred
#             print("SVM Model Info for Ticker: "+i)
#             print("Accuracy:",metrics.accuracy_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction']))
#             model_dict[i]['Accuracy'] = metrics.accuracy_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction'])
#             print("Precision:",metrics.precision_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction'],pos_label=str(1),average="macro"))
#             model_dict[i]['Precision'] = metrics.precision_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction'],pos_label=str(1),average="macro")
#             print("Recall:",metrics.recall_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction'],pos_label=str(1),average="macro"))
#             model_dict[i]['Recall'] = metrics.recall_score(model_dict[i]['Y Test'], model_dict[i]['Y Prediction'],pos_label=str(1),average="macro")
#             #print("#################### \n")
#         except: 
#             a.append(i)


In [52]:
# for i in stock_data:
#     #todo is this rly smart
#     stock_data[i]['Returns'] = np.log(stock_data[i]['adj_close']/stock_data[i]['adj_close'].shift(1)) 

#     prediction_length = len(model_dict[i]['Y Prediction'])

#     stock_data[i]['SVM Signal'] = 0
#     stock_data[i]['SVM Returns'] = 0
#     stock_data[i]['Total Strat Returns'] = 0
#     stock_data[i]['Market Returns'] = 0

#     Signal_Column = stock_data[i].columns.get_loc('SVM Signal')
#     Strat_Column = stock_data[i].columns.get_loc('SVM Returns')
#     Return_Column = stock_data[i].columns.get_loc('Total Strat Returns')
#     Market_Column = stock_data[i].columns.get_loc('Market Returns')
        
#     stock_data[i].iloc[-prediction_length:,Signal_Column] = list(map(int,model_dict[i]['Y Prediction']))
#     stock_data[i]['SVM Returns'] = stock_data[i]['SVM Signal'] * stock_data[i]['Returns'].shift(1)

#     stock_data[i].iloc[-prediction_length:,Return_Column] = np.nancumsum(stock_data[i]['SVM Returns'][-prediction_length:])
#     stock_data[i].iloc[-prediction_length:,Market_Column] = np.nancumsum(stock_data[i]['Returns'][-prediction_length:])
#     # print(stock_data[i]['Total Strat Returns'].head)

#     # model_dict[i]['Sharpe_Ratio'] = (stock_data[i]['Total Strat Returns'][-1] - stock_data[i]['Market Returns'][-1])/ \
#     #                 np.nanstd(stock_data[i]['Total Strat Returns'][-prediction_length:])